-- CMDB
CREATE TABLE `ops_cmdb_attribute_c` (
                                        `id` varchar(50) NOT NULL COMMENT '主键',
                                        `code` varchar(50) DEFAULT NULL COMMENT '字段',
                                        `name` varchar(50) DEFAULT NULL COMMENT '名称',
                                        `sort` int(11) DEFAULT '0' COMMENT '排序',
                                        `create_by` varchar(18) DEFAULT NULL COMMENT '创建人ID',
                                        `create_time` datetime DEFAULT NULL COMMENT '创建时间',
                                        `update_by` varchar(18) DEFAULT NULL COMMENT '修改人ID',
                                        `update_time` datetime DEFAULT NULL COMMENT '修改时间',
                                        `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否已删除',
                                        `delete_by` varchar(18) DEFAULT NULL COMMENT '删除人ID',
                                        `delete_time` datetime DEFAULT NULL COMMENT '删除时间',
                                        `version` int(11) DEFAULT '1',
                                        `tenant_id` varchar(18) DEFAULT NULL COMMENT '租户',
                                        PRIMARY KEY (`id`) USING BTREE,
                                        UNIQUE KEY `cmdbAttributeCind1` (`code`,`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='属性字段';


CREATE TABLE `ops_cmdb_log` (
                                `id` varchar(50) NOT NULL COMMENT '主键',
                                `model_id` varchar(50) DEFAULT NULL COMMENT '模型',
                                `obj_id` varchar(50) DEFAULT NULL COMMENT '对象',
                                `log_level` varchar(50) DEFAULT NULL COMMENT '日志级别',
                                `trace_id` varchar(50) DEFAULT NULL COMMENT 'TRACE',
                                `log_record` varchar(1000) DEFAULT NULL COMMENT '日志',
                                `rcd_time` datetime DEFAULT NULL COMMENT '时间',
                                `notes` varchar(500) DEFAULT NULL COMMENT '备注',
                                `create_by` varchar(18) DEFAULT NULL COMMENT '创建人ID',
                                `create_time` datetime DEFAULT NULL COMMENT '创建时间',
                                `update_by` varchar(18) DEFAULT NULL COMMENT '修改人ID',
                                `update_time` datetime DEFAULT NULL COMMENT '修改时间',
                                `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否已删除',
                                `delete_by` varchar(18) DEFAULT NULL COMMENT '删除人ID',
                                `delete_time` datetime DEFAULT NULL COMMENT '删除时间',
                                `version` int(11) DEFAULT '1',
                                `tenant_id` varchar(18) DEFAULT NULL COMMENT '租户',
                                PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='配置日志';

CREATE TABLE `ops_cmdb_model` (
                                  `id` varchar(50) NOT NULL COMMENT '主键',
                                  `parent_id` varchar(50) DEFAULT NULL COMMENT '父节点',
                                  `status` varchar(50) DEFAULT 'disable' COMMENT '状态',
                                  `hierarchy` varchar(1000) DEFAULT NULL COMMENT '节点路径',
                                  `hierarchy_name` varchar(1000) DEFAULT NULL COMMENT '节点路径名称',
                                  `name` varchar(100) DEFAULT NULL COMMENT '名称',
                                  `full_name` varchar(500) DEFAULT NULL COMMENT '全称',
                                  `code` varchar(50) DEFAULT NULL COMMENT '编码',
                                  `model_type` varchar(50) DEFAULT NULL COMMENT '模型类型',
                                  `source_type` varchar(50) DEFAULT 'none' COMMENT '数据来源',
                                  `source` varchar(1000) DEFAULT NULL COMMENT '来源',
                                  `data_source` varchar(50) DEFAULT 'none' COMMENT '来源方式',
                                  `association_type` varchar(50) DEFAULT 'none' COMMENT '关联方式',
                                  `storage_type` varchar(50) DEFAULT 'direct' COMMENT '存储方式',
                                  `relation_code` varchar(50) DEFAULT NULL COMMENT '关联编码',
                                  `sort` int(11) DEFAULT '0' COMMENT '排序',
                                  `notes` varchar(500) DEFAULT NULL COMMENT '备注',
                                  `create_by` varchar(18) DEFAULT NULL COMMENT '创建人ID',
                                  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
                                  `update_by` varchar(18) DEFAULT NULL COMMENT '修改人ID',
                                  `update_time` datetime DEFAULT NULL COMMENT '修改时间',
                                  `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否已删除',
                                  `delete_by` varchar(18) DEFAULT NULL COMMENT '删除人ID',
                                  `delete_time` datetime DEFAULT NULL COMMENT '删除时间',
                                  `version` int(11) DEFAULT '1',
                                  `tenant_id` varchar(18) DEFAULT NULL COMMENT '租户',
                                  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='配置库';


CREATE TABLE `ops_cmdb_model_v` (
                                    `id` varchar(50) NOT NULL COMMENT '主键',
                                    `pid` varchar(50) DEFAULT '0' COMMENT '父',
                                    `model_id` varchar(50) DEFAULT '0' COMMENT '当前模型',
                                    `data_trace_code` varchar(50) DEFAULT '0' COMMENT '数据跟踪',
                                    `v_status` varchar(50) DEFAULT NULL COMMENT '状态',
                                    `v_version` int(11) DEFAULT '0' COMMENT '版本',
                                    `obj_source_id` varchar(50) DEFAULT NULL COMMENT '对象',
                                    `name` varchar(200) DEFAULT NULL COMMENT '名称',
                                    `desc` varchar(500) DEFAULT NULL COMMENT '描述',
                                    `s1` varchar(50) DEFAULT NULL COMMENT '内容',
                                    `s2` varchar(50) DEFAULT NULL COMMENT '内容',
                                    `s3` varchar(50) DEFAULT NULL COMMENT '内容',
                                    `s4` varchar(50) DEFAULT NULL COMMENT '内容',
                                    `s5` varchar(50) DEFAULT NULL COMMENT '内容',
                                    `s6` varchar(50) DEFAULT NULL COMMENT '内容',
                                    `s7` varchar(50) DEFAULT NULL COMMENT '内容',
                                    `s8` varchar(50) DEFAULT NULL COMMENT '内容',
                                    `m1` varchar(50) DEFAULT NULL COMMENT '内容',
                                    `m2` varchar(200) DEFAULT NULL COMMENT '内容',
                                    `m3` varchar(200) DEFAULT NULL COMMENT '内容',
                                    `m4` varchar(200) DEFAULT NULL COMMENT '内容',
                                    `m5` varchar(200) DEFAULT NULL COMMENT '内容',
                                    `m6` varchar(200) DEFAULT NULL COMMENT '内容',
                                    `m7` varchar(200) DEFAULT NULL COMMENT '内容',
                                    `m8` varchar(200) DEFAULT NULL COMMENT '内容',
                                    `m9` varchar(200) DEFAULT NULL COMMENT '内容',
                                    `m10` varchar(200) DEFAULT NULL COMMENT '内容',
                                    `bs1` varchar(1000) DEFAULT NULL COMMENT '内容',
                                    `bs2` varchar(1000) DEFAULT NULL COMMENT '内容',
                                    `bs3` varchar(1000) DEFAULT NULL COMMENT '内容',
                                    `i1` int(11) DEFAULT NULL COMMENT '内容',
                                    `i2` int(11) DEFAULT NULL COMMENT '内容',
                                    `i3` int(11) DEFAULT NULL COMMENT '内容',
                                    `i4` int(11) DEFAULT NULL COMMENT '内容',
                                    `i5` int(11) DEFAULT NULL COMMENT '内容',
                                    `i6` int(11) DEFAULT NULL COMMENT '内容',
                                    `i7` int(11) DEFAULT NULL COMMENT '内容',
                                    `i8` int(11) DEFAULT NULL COMMENT '内容',
                                    `i9` int(11) DEFAULT NULL COMMENT '内容',
                                    `i10` int(11) DEFAULT NULL COMMENT '内容',
                                    `d1` decimal(10,2) DEFAULT NULL COMMENT '内容',
                                    `d2` decimal(10,2) DEFAULT NULL COMMENT '内容',
                                    `d3` decimal(10,2) DEFAULT NULL COMMENT '内容',
                                    `d4` decimal(10,2) DEFAULT NULL COMMENT '内容',
                                    `d5` decimal(10,2) DEFAULT NULL COMMENT '内容',
                                    `d6` decimal(10,2) DEFAULT NULL COMMENT '内容',
                                    `d7` decimal(10,2) DEFAULT NULL COMMENT '内容',
                                    `d8` decimal(10,2) DEFAULT NULL COMMENT '内容',
                                    `da1` date DEFAULT NULL COMMENT '内容',
                                    `da2` date DEFAULT NULL COMMENT '内容',
                                    `da3` date DEFAULT NULL COMMENT '内容',
                                    `notes` varchar(500) DEFAULT NULL COMMENT '备注',
                                    `create_by` varchar(18) DEFAULT NULL COMMENT '创建人ID',
                                    `create_time` datetime DEFAULT NULL COMMENT '创建时间',
                                    `update_by` varchar(18) DEFAULT NULL COMMENT '修改人ID',
                                    `update_time` datetime DEFAULT NULL COMMENT '修改时间',
                                    `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否已删除',
                                    `delete_by` varchar(18) DEFAULT NULL COMMENT '删除人ID',
                                    `delete_time` datetime DEFAULT NULL COMMENT '删除时间',
                                    `version` int(11) DEFAULT '1',
                                    `tenant_id` varchar(18) DEFAULT NULL COMMENT '租户',
                                    PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='配置值';

CREATE TABLE `ops_cmdb_obj_attribute` (
                                          `id` varchar(50) NOT NULL COMMENT '主键',
                                          `model_id` varchar(50) DEFAULT NULL COMMENT '模型对象',
                                          `status` varchar(50) DEFAULT NULL COMMENT '状态',
                                          `attribute_name` varchar(50) DEFAULT NULL COMMENT '属性名称',
                                          `attribute_type` varchar(50) DEFAULT NULL COMMENT '属性类型',
                                          `attribute_col_source` varchar(50) DEFAULT NULL COMMENT '字段来源',
                                          `attribute_col_fill` varchar(50) DEFAULT NULL COMMENT '字段填充',
                                          `attribute_col_alias` varchar(50) DEFAULT NULL COMMENT '填充别名',
                                          `sort` int(11) DEFAULT '0' COMMENT '排序',
                                          `notes` varchar(500) DEFAULT NULL COMMENT '备注',
                                          `create_by` varchar(18) DEFAULT NULL COMMENT '创建人ID',
                                          `create_time` datetime DEFAULT NULL COMMENT '创建时间',
                                          `update_by` varchar(18) DEFAULT NULL COMMENT '修改人ID',
                                          `update_time` datetime DEFAULT NULL COMMENT '修改时间',
                                          `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否已删除',
                                          `delete_by` varchar(18) DEFAULT NULL COMMENT '删除人ID',
                                          `delete_time` datetime DEFAULT NULL COMMENT '删除时间',
                                          `version` int(11) DEFAULT '1',
                                          `tenant_id` varchar(18) DEFAULT NULL COMMENT '租户',
                                          PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='配置属性';