CREATE TABLE `ops_deploy_standard` (
                                       `id` varchar(50) NOT NULL COMMENT '主键',
                                       `name` varchar(50) DEFAULT NULL COMMENT '名称',
                                       `type_id` varchar(50) DEFAULT NULL COMMENT '类型',
                                       `user_content` varchar(1000) DEFAULT NULL COMMENT '用户标准',
                                       `dir_content` varchar(1000) DEFAULT NULL COMMENT '目录标准',
                                       `deploy_content` varchar(1000) DEFAULT NULL COMMENT '部署标准',
                                       `create_db_content` varchar(1000) DEFAULT NULL COMMENT '实例标准',
                                       `maintenance_content` varchar(1000) DEFAULT NULL COMMENT '日常维护',
                                       `backup_script` varchar(1000) DEFAULT NULL COMMENT '备份脚本',
                                       `release_version` varchar(50) DEFAULT NULL COMMENT '版本',
                                       `attach_id` varchar(500) DEFAULT NULL COMMENT '附件人',
                                       `notes` varchar(500) DEFAULT NULL COMMENT '备注',
                                       `create_by` varchar(18) DEFAULT NULL COMMENT '创建人ID',
                                       `create_time` datetime DEFAULT NULL COMMENT '创建时间',
                                       `update_by` varchar(18) DEFAULT NULL COMMENT '修改人ID',
                                       `update_time` datetime DEFAULT NULL COMMENT '修改时间',
                                       `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否已删除',
                                       `delete_by` varchar(18) DEFAULT NULL COMMENT '删除人ID',
                                       `delete_time` datetime DEFAULT NULL COMMENT '删除时间',
                                       `version` int(11) NOT NULL DEFAULT '1',
                                       `tenant_id` varchar(18) DEFAULT NULL COMMENT '租户',
                                       PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='部署标准';