/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.niuys.gdzc.web.struts.form;

import org.apache.struts.validator.ValidatorForm;

public class ZCForm extends ValidatorForm {
	private String zc_id;
	private String zc_no;
	private String zc_name;
	private String zc_price;
	private String zc_factory;
	private String zc_produceTime;
	private String zc_buyTime;
	private String zc_buyer;
	private String zc_type;
	private String zc_status;
	private String zc_bzxx;
	
	
	public ZCForm() {
		super();
	}
	public String getZc_id() {
		return zc_id;
	}
	public void setZc_id(String zc_id) {
		this.zc_id = zc_id;
	}
	public String getZc_no() {
		return zc_no;
	}
	public void setZc_no(String zc_no) {
		this.zc_no = zc_no;
	}
	public String getZc_name() {
		return zc_name;
	}
	public void setZc_name(String zc_name) {
		this.zc_name = zc_name;
	}
	public String getZc_price() {
		return zc_price;
	}
	public void setZc_price(String zc_price) {
		this.zc_price = zc_price;
	}
	public String getZc_factory() {
		return zc_factory;
	}
	public void setZc_factory(String zc_factory) {
		this.zc_factory = zc_factory;
	}
	public String getZc_produceTime() {
		return zc_produceTime;
	}
	public void setZc_produceTime(String zc_produceTime) {
		this.zc_produceTime = zc_produceTime;
	}
	public String getZc_buyTime() {
		return zc_buyTime;
	}
	public void setZc_buyTime(String zc_buyTime) {
		this.zc_buyTime = zc_buyTime;
	}
	public String getZc_buyer() {
		return zc_buyer;
	}
	public void setZc_buyer(String zc_buyer) {
		this.zc_buyer = zc_buyer;
	}
	public String getZc_type() {
		return zc_type;
	}
	public void setZc_type(String zc_type) {
		this.zc_type = zc_type;
	}
	public String getZc_status() {
		return zc_status;
	}
	public void setZc_status(String zc_status) {
		this.zc_status = zc_status;
	}
	public String getZc_bzxx() {
		return zc_bzxx;
	}
	public void setZc_bzxx(String zc_bzxx) {
		this.zc_bzxx = zc_bzxx;
	}
}